Exercises/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Exercises.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Exercises/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Exercises.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Exercises/Pages/Lesson1/Assignment1.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Exercises.Pages.Lesson1
{
    public class Assignment1 : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Exercises/Pages/Lesson1/Assignment2.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Exercises.Pages.Lesson1
{


    public class Exercise2 : PageModel
    {
        public enum Direction
        {
            Left, Right, Forward, Backward
        }

        public void OnGet()
        {
        }
    }
}

Exercises/Pages/Lesson1/Assignment3.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Exercises.Pages.Lesson1
{
    public class Assignment3 : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Exercises/Pages/Lesson1/Assignment4.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Exercises.Pages.Lesson1
{
    public class Assignment4 : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Exercises/Pages/Lesson1/Assignment5.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Exercises.Pages.Lesson1
{
    public class Assignment5 : PageModel
    {
        public class MoodCounter {
            public int Happy { get; set; }
            public int Disappointed { get; set; }
            public int Angry { get; set; }
        }

        public void OnGet()
        {
        }
    }
}

Exercises/Pages/Lesson3/Ober.cshtml.cs
using System.Collections.Generic;
using Exercises.Pages.Lesson3.Models;
using Exercises.Pages.Lesson3.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Exercises.Pages.Lesson3
{
    public class Ober : PageModel
    {
        private OrderRepository _orderRepository;

        [BindProperty]
        public int? TableNr { get; set; }

        [BindProperty]
        public int? CategoryId { get; set; }

        [BindProperty]
        public int? ProductId { get; set; }

        public List<Category> Categories { get; set; }
        public List<Product> Products { get; set; }

        public List<OrderRepository.TableOrderViewModel> TableOrders { get; set; }

        public List<OrderLine> TableOrdersWithRelationship { get; set; }

        public Ober()
        {
            _orderRepository = new OrderRepository(new DbUtils().GetDbConnection());
        }

        private void LoadData()
        {
            Categories = _orderRepository.GetCategories();

            if (CategoryId.HasValue)
            {
                Products = _orderRepository.GetProducts(CategoryId.Value);
            }

            if (TableNr.HasValue)
            {
                TableOrdersWithRelationship = _orderRepository.GetTableOrdersWithRelationships(TableNr.Value);

                TableOrders = _orderRepository.GetTableOrders(TableNr.Value);
            }
        }



        public void OnGet()
        {
            LoadData();
        }

        public void OnPostSelectTable()
        {
            LoadData();
        }

        public void OnPostSelectCategory()
        {
            LoadData();
        }

        public void OnPostAddProductToOrder()
        {
            _orderRepository.AddOrder(TableNr.Value, ProductId.Value);

            LoadData();
        }

        public void OnPostPay()
        {
            _orderRepository.Pay(TableNr.Value);

            LoadData();
        }

    }
}

Exercises/Pages/Lesson3/Overview.cshtml.cs
using System.Collections.Generic;
using Exercises.Pages.Lesson3.Models;
using Exercises.Pages.Lesson3.Repositories;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Exercises.Pages.Lesson3
{
    public class Overview : PageModel
    {
        public List<CostObject> CostObjects { get; set; }
        public List<CostObjectRepository.BillLine> BillLines { get; set; } = null;
        public CostObjectRepository.TotalPrice TotalPrice { get; set; }

        public int? CostObjectId { get; set; }
        public void OnGet(int? costObjectId)
        {
            CostObjectId = costObjectId;

            var costObjectRepository = new CostObjectRepository(new DbUtils().GetDbConnection());
            CostObjects = costObjectRepository.GetAll();

            if (costObjectId.HasValue)
            {
                BillLines = costObjectRepository.GetBillLines(costObjectId.Value);
                TotalPrice = costObjectRepository.GetTotalBillPrice(costObjectId.Value);
            }
        }


    }
}

Exercises/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Exercises.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Exercises/Pages/Lesson1/Assignment1.cshtml
@page
@model Exercises.Pages.Lesson1.Assignment1

@{
    Layout = null;
}

<div>
    <p>
        <span id="scoreHome">###</span> - <span id="scoreAway">###</span>
    </p>
    <div>
        <a id="incrementHome" href="###">Home ++</a>
        <a id="decrementHome" href="###">Home --</a>

        <a id="incrementAway" href="###">Away ++</a>
        <a id="decrementAway" href="###">Away --</a>
    </div>
    <div>
        <a id="reset" href="###">Reset</a>
    </div>
</div>

Exercises/Pages/Lesson1/Assignment2.cshtml
@page
@model Exercises.Pages.Lesson1.Exercise2

@{
    Layout = null;
}

@{

}

<a href="###">Left</a>
<a href="###">Right</a>
<a href="###">Forward</a>
<a href="###">Backward</a>

<hr>
<a href="###">Clear</a>

<hr>

<ul id="route">
    <!-- geeft de route weer, met onderstaande -->
    <li>Left</li>
    <li>Right</li>
    <li>Forward</li>
    <li>Backward</li>
</ul>

Exercises/Pages/Lesson1/Assignment3.cshtml
@page
@model Exercises.Pages.Lesson1.Assignment3

@{
    Layout = null;
}

<div>
    <p id="result">###</p>
</div>

<form method="post" id="calculatorForm">
    <input type="hidden" ###>
    <input type="text" id="input" name="input">
    <button name="addBtn" id="addBtn" type="submit" ###>+</button>
    <button name="subBtn" id="subBtn" type="submit" ###>-</button>
    <button name="mulBtn" id="mulBtn" type="submit" ###>*</button>
    <button name="divBtn" id="divBtn" type="submit" ###>/</button>
</form>

Exercises/Pages/Lesson1/Assignment4.cshtml
@page /* plaats hier de route + constraints */
@model Exercises.Pages.Lesson1.Assignment4

@{
    Layout = null;
}

<h1 id="categoryHeading">###</h1>
<h2 id="subCategoryHeading">###</h2>
<h3 id="productIdHeading">###</h3>

Exercises/Pages/Lesson1/Assignment5.cshtml
@page
@model Exercises.Pages.Lesson1.Assignment5

@{
    Layout = null;
}

<div>
    <form method="post">
        <h1>Happy: <span id="happyCount">###</span>
            <button id="btnHappy" type="submit" ###>Happy++</button>
        </h1>

        <h1>Disappointed: <span id="disappointedCount">###</span>
            <button id="btnDisappointed" type="submit" ###>Disappointed++</button>
        </h1>

        <h1>Angry: <span id="angryCount">###</span>
            <button id="btnAngry" type="submit" ###>Angry++</button>
        </h1>

        <hr>

        <button id="btnDeleteCookie" type="submit" ###>Delete Cookie</button>
    </form>
</div>

Exercises/Pages/Lesson3/Ober.cshtml
@page
@model Exercises.Pages.Lesson3.Ober

@{
    Layout = null;
}

<style>
    .order-overview td {
        border: 1px solid black;
    }
</style>

<div>
    <div>Tafel: @Model.TableNr</div>
    @if (Model.TableNr.HasValue && Model.TableOrders.Any())
    {
        <div>
            <form method="post" asp-page-handler="pay">
                <input type="hidden" asp-for="TableNr">
                <button type="submit">Pay &euro;@Model.TableOrders.Sum(x => x.TotalPrice)</button>
            </form>
        </div>
    }
</div>

<hr>

<div>
    <form name="tableNrSelectForm" method="post" asp-page-handler="selectTable">
        <select name="tableNr">
            @foreach (var tableNr in Enumerable.Range(1, 10))
            {
                if (tableNr == Model.TableNr)
                {
                    <option value="@tableNr" selected>Tafel Nr: @tableNr</option>
                }
                else
                {
                    <option value="@tableNr">Tafel Nr: @tableNr</option>
                }
            }
        </select>¡
        <button type="submit">Selecteer tafel</button>
    </form>
</div>

@if (Model.TableNr.HasValue)
{
    <div>
        <form name="categorySelectForm" method="post" asp-page-handler="selectCategory">
            <input type="hidden" asp-for="TableNr">
            <select name="CategoryId" asp-for="CategoryId">
                @foreach (var category in Model.Categories)
                {
                    if (category.CategoryId == Model.CategoryId)
                    {
                        <option value="@category.CategoryId" selected>@category.Name</option>
                    }
                    else
                    {
                        <option value="@category.CategoryId">@category.Name</option>
                    }
                }
            </select>
            <button type="submit">Selecteer category</button>
        </form>
    </div>
}

@if (Model.Products != null)
{
    <div>
        <form name="productSelectForm" method="post" asp-page-handler="addProductToOrder">
            <input type="hidden" asp-for="TableNr">
            <input type="hidden" asp-for="CategoryId">
            <select name="ProductId">
                @foreach (var product in Model.Products)
                {
                    if (product.ProductId == Model.ProductId)
                    {
                        <option value="@product.ProductId" selected>@product.Name</option>
                    }
                    else
                    {
                        <option value="@product.ProductId">@product.Name</option>
                    }
                }
            </select>
            <button type="submit">Product toevoegen</button>
        </form>
    </div>
}

@if (Model.TableOrders != null && Model.TableOrders.Any())
{
    <div>

        <table class="order-overview">
            <thead>
            <tr>
                <th>Category</th>
                <th>Product</th>
                <th>Aantal</th>
                <th>Stuk Price</th>
                <th>Totaal Prijs</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var tableOrder in Model.TableOrders)
            {
                <tr>
                    <td>
                        @tableOrder.CategoryName
                    </td>
                    <td>
                        @tableOrder.ProductName
                    </td>
                    <td>
                        @tableOrder.Amount
                    </td>
                    <td>
                        &euro; @tableOrder.Price
                    </td>
                    <td>
                        &euro; @tableOrder.TotalPrice
                    </td>
                    <td>
                        &nbsp;
                    </td>
                    <td>
                        <form asp-page-handler="addProductToOrder">
                            <input type="hidden" asp-for="TableNr">
                            <input type="hidden" asp-for="CategoryId">
                            <input type="hidden" name="ProductId" value="@tableOrder.ProductId">
                            <button type="submit">++</button>
                        </form>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
}
else
{
    <div>Geen Orders</div>
}

<hr>
<hr>
<h1>Manier 2 met Relationships</h1>
@if (Model.TableOrdersWithRelationship != null && Model.TableOrdersWithRelationship.Any())
{
    <div>
        <table class="order-overview">
            <thead>
            <tr>
                <th>Category</th>
                <th>Product</th>
                <th>Aantal</th>
                <th>Stuk Price</th>
                <th>Totaal Prijs</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var orderLine in Model.TableOrdersWithRelationship)
            {
                <tr>
                    <td>
                        @orderLine.Product.Category.Name
                    </td>
                    <td>
                        @orderLine.Product.Name
                    </td>
                    <td>
                        @orderLine.Amount
                    </td>
                    <td>
                        &euro; @orderLine.Product.Price
                    </td>
                    <td>
                        &euro; @(orderLine.Product.Price * orderLine.Amount)
                    </td>
                    <td>
                        &nbsp;
                    </td>
                    <td>
                        <form asp-page-handler="addProductToOrder">
                            <input type="hidden" asp-for="TableNr">
                            <input type="hidden" asp-for="CategoryId">
                            <input type="hidden" name="ProductId" value="@orderLine.Product.ProductId">
                            <button type="submit">++</button>
                        </form>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
}
else
{
    <div>Geen Orders</div>
}

Exercises/Pages/Lesson3/Overview.cshtml
@page "{costObjectId:int?}"
@model Exercises.Pages.Lesson3.Overview

@{
    Layout = null;
}

<table id="costObjectsTable">
@foreach (var costObject in Model.CostObjects)
{
    <tr style="@(costObject.CostObjectId == Model.CostObjectId ? "background-color: lightblue" : "")">
        <td>@costObject.Name</td>
        <td>@costObject.Budget</td>
        <td>@costObject.TelNr</td>
        <td>@costObject.Email</td>
        <td><a class="displayBillBtn" id="@("costObjectId"+costObject.CostObjectId)" asp-route-costObjectId="@costObject.CostObjectId">Display Bill</a></td>
    </tr>
}
</table>
<hr>
@if (@Model.BillLines != null && Model.BillLines.Any())
{
    <table id="billLinesTable">
        @foreach (var billLine in Model.BillLines)
        {
            <tr>
                <td>@billLine.ProductName</td>
                <td>@billLine.CategoryName</td>
                <td>@billLine.ProductPrice</td>
                <td>@billLine.ProductOrderedAmount</td>
                <td>@billLine.TotalProductPrice</td>
            </tr>
        }
        <tr>
            <td colspan="4"></td>
            <td>@Model.TotalPrice.Total</td>
        </tr>
    </table>
}
else
{
    <h1 class="noOrder">No Orders</h1>
}