Examples/Pages/Lesson1/Cookies.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class Cookies : PageModel
    {
        public int Counter { get; set; } = 0;

        public void OnGet(string action = "")
        {
            action = action.ToLower();

            string counterStr = Request.Cookies["counter"];
            if (counterStr == null) //cookie is not set (first time request or after reset)
            {
                Response.Cookies.Append("counter", Counter.ToString());
            }
            else
            {
                Counter = int.Parse(counterStr);  //Convert.ToInt32(counterStr)

                if (action == "increment")
                {
                    Counter++;
                    Response.Cookies.Append("counter", Counter.ToString());
                } else if (action == "decrement")
                {
                    Counter--;
                    Response.Cookies.Append("counter", Counter.ToString());
                } else if (action == "reset")
                {
                    //counter = 0;
                    Response.Cookies.Delete("counter");
                }
            }
        }
    }
}

Examples/Pages/Lesson1/GetIncrementCounter.cshtml.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class IncrementCounter : PageModel
    {
        public int Counter { get; set; } = 0;

        public void OnGet()
        {
            if (Request.Query.ContainsKey("count"))
            {
                Counter = Convert.ToInt32(Request.Query["count"].First());
            }

            Counter++;
        }
    }
}

Examples/Pages/Lesson1/GetRequest.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class GetRequest : PageModel
    {
        public string Name { get; set; }

        public void OnGet()
        {
            if (Request.Query.ContainsKey("naam") && !string.IsNullOrWhiteSpace(Request.Query["naam"]))
            {
                Name = Request.Query["naam"].First().ToUpper();
            }
        }
    }
}

Examples/Pages/Lesson1/HiddenFormFields.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class HiddenFormFields : PageModel
    {
        public void OnGet()
        {

        }

        [BindProperty]
        public string Action { get; set; }

        public int ProductId { get; set; }

        public void OnPost([FromForm]int productId)
        {
            ProductId = productId;
        }
    }
}

Examples/Pages/Lesson1/NonWorkingCounter.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class NonWorkingCounter : PageModel
    {
        public int Counter { get; set; }

        public void OnGet()
        {
            Counter++;
            //this counter will never be greater than 1,
            //that's why we need state management to maintain state over multiple HTTP Request!
        }
    }
}

Examples/Pages/Lesson1/PageCentric.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class PageCentricExample : PageModel
    {
        public class Todo
        {
            public int TodoId { get; set; }
            public string Name { get; set; }
            public bool Completed { get; set; }
        }

        public List<Todo> Todos { get; set; }

        public void OnGet()
        {
            Todos = new List<Todo>();

            for (int i = 1; i <= 10; i++)
            {
                var todo = new Todo();
                todo.TodoId = i;
                todo.Name = "Item " + i;
                todo.Completed = i % 2 == 0;

                Todos.Add(todo);
            }
        }

    }
}

Examples/Pages/Lesson1/PageHandler.cshtml.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class PageHandler : PageModel
    {
        public int Counter { get; set; } = 0;

        public void OnGet()
        {

        }

        public void OnPostIncrement()
        {
            Counter = Convert.ToInt32(Request.Form["count"].First());

            Counter++;
        }

        public void OnPostDecrement()
        {
            Counter = Convert.ToInt32(Request.Form["count"].First());

            Counter--;
        }

        public void OnGetIncrement([FromQuery] int count)
        {
            Counter = count + 1;
        }

        public void OnGetDecrement([FromQuery] int count)
        {
            Counter = count - 1;
        }
    }
}

Examples/Pages/Lesson1/PostRequest.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class PostRequest : PageModel
    {
        public string Name { get; set; }

        public void OnGet()
        {

        }

        public void OnPost()
        {
            if (Request.Query.ContainsKey("naam") && !string.IsNullOrWhiteSpace(Request.Query["naam"]))
            {
                Name = Request.Form["naam"].First().ToUpper();
            }
        }
    }
}

Examples/Pages/Lesson1/QueryStringsMethodBindProperty.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class QueryStringsMethodBindProperty : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string Firstname { get; set; }

        [BindProperty(SupportsGet = true)]
        public IEnumerable<string> MiddleNames { get; set; } = new List<string>();

        [BindProperty(SupportsGet = true)]
        public string Lastname { get; set; }

        public void OnGet([FromQuery] string firstname, [FromQuery]IEnumerable<string> middleNames, [FromQuery]string lastname)
        {
            Firstname = firstname;
            MiddleNames = middleNames.Where(x => !string.IsNullOrWhiteSpace(x));
            Lastname = lastname;
        }


    }
}

Examples/Pages/Lesson1/QueryStringsMethodParameter.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class QueryStringsMethodParameter : PageModel
    {
        public string Firstname { get; set; }
        public IEnumerable<string> MiddleNames { get; set; } = new List<string>();
        public string Lastname { get; set; }

        public void OnGet([FromQuery] string firstname, [FromQuery]IEnumerable<string> middleNames, [FromQuery]string lastname)
        {
            Firstname = firstname;
            MiddleNames = middleNames.Where(x => !string.IsNullOrWhiteSpace(x));
            Lastname = lastname;
        }


    }
}

Examples/Pages/Lesson1/QueryStringsMethodRequest.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class QueryStringsMethodRequest : PageModel
    {
        public string Firstname { get; set; }

        public IEnumerable<string> MiddleNames { get; set; } = new List<string>();

        public string Lastname { get; set; }

        //[FromQuery] string firstname, [FromQuery]IEnumerable<string> middleNames, [FromQuery]string lastname
        public void OnGet()
        {
            Firstname = Request.Query["firstname"];
            MiddleNames = Request.Query["middleNames"].Where(x => !string.IsNullOrWhiteSpace(x));
            Lastname = Request.Query["lastname"];
        }


    }
}

Examples/Pages/Lesson1/Redirect.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class Redirect : PageModel
    {
        public int Count { get; set; } = 0;

        public IActionResult OnGet(int? countParameter)
        {
            if (countParameter != null)
            {
                Count = countParameter.Value;
            }

            Count++;

            if (Count < 10)
            {
                return RedirectToPage("Redirect", new
                {
                    countParameter = Count
                });
            }
            else
            {
                return Page();
            }
        }
    }
}

Examples/Pages/Lesson1/RouteParameters.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    //Let op de @page attribute en optionele argumenten!
    // https://localhost:5001/Lesson1/RouteParameters/increment/1
    // https://www.learnrazorpages.com/razor-pages/routing
    // https://www.mikesdotnetting.com/article/339/optional-parameters-in-razor-pages-routing#:~:text=Razor%20Pages%20routing%20is%20based,to%20permit%20multiple%20optional%20parameters.
    public class RouteParameters : PageModel
    {
        //[BindProperty(SupportsGet = true)]
        public int Count { get; set; } = 0;

        //[BindProperty(SupportsGet = true)]
        //public string Action { get; set; }

        public void OnGet([FromRoute]int count, [FromRoute]string action)
        {
            //Request.RouteValues["count"]
            //Request.RouteValues["action"]

            if (action == "")
            {
                Count = 0;
            }
            else if (action == "increment")
            {
                Count = count + 1;
            }
            else if (action == "decrement")
            {
                Count = count - 1;
            }
        }
    }
}

Examples/Pages/Lesson1/SendDataWithRequest.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class PostRequestWithParameterBinding : PageModel
    {
        public string Firstname { get; set; }
        public string Surname { get; set; }

        [BindProperty]
        public string Nickname { get; set; }


        [BindProperty(SupportsGet = true)] public string NicknameGet { get; set; }

        public void OnGet(string surname)
        {
            if (Request.Query.ContainsKey("firstname") && !string.IsNullOrWhiteSpace(Request.Query["firstname"]))
            {
                Firstname = Request.Query["firstname"].First().ToUpper();
            }

            Surname = surname;
        }

        public void OnPost(string surname)
        {
            if (Request.Form.ContainsKey("firstname") && !string.IsNullOrWhiteSpace(Request.Form["firstname"]))
            {
                Firstname = Request.Form["firstname"].First().ToUpper();
            }

            Surname = surname;
        }
    }
}

Examples/Pages/Lesson1/SessionStoreObject.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class SessionStoreObject : PageModel
    {
        public ActionCounter ActionCounter { get; set; }
        public void OnGet(string action = "")
        {
            if (action == "removeSession")
            {
                HttpContext.Session.Remove("actionCounter");
            }

            ActionCounter actionCounter = HttpContext.Session.Get<ActionCounter>("actionCounter");
            if (actionCounter == null)
            {
                actionCounter = new ActionCounter();
            }

            if (action != "" && action != "removeSession")
            {
                actionCounter.AddAction(action);
            }

            HttpContext.Session.Set<ActionCounter>("actionCounter", actionCounter);

            ActionCounter = actionCounter;
        }
    }

    public class ActionCounter
    {
        public List<string> Actions { get; set; } = new List<string>();

        public void AddAction(string action)
        {
            Actions.Add(action.ToLower());
        }

        public int CalculateResult()
        {
            int count = 0;

            foreach (var action in Actions)
            {
                if (action == "increment")
                {
                    count++;
                }
                else if (action == "decrement")
                {
                    count--;
                } else if (action == "reset")
                {
                    count = 0;
                }
            }

            return count;
        }
    }


}

Examples/Pages/Lesson1/Sessions.cshtml.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{

    //https://www.learnrazorpages.com/razor-pages/session-state
    public class Sessions : PageModel
    {
        public int Count { get; set; }

        public void OnGet()
        {
            string strCount = HttpContext.Session.GetString("count");
            if (strCount != null)
            {
                Count = Convert.ToInt32(strCount);
                Count++;
            }
            else
            {
                Count = 0;
            }

            HttpContext.Session.SetString("count", Count.ToString());
        }
    }
}

Examples/Pages/Lesson1/SetTempData.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class SetTempData : PageModel
    {
        public void OnGet() {
        }

        public RedirectToPageResult OnPost(int lievelingsgetal)
        {
            TempData["Lievelingsgetal"] = lievelingsgetal.ToString();
            return RedirectToPage("ShowTempData");
        }
    }
}

Examples/Pages/Lesson1/ShowTempData.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson1
{
    public class ShowTempData : PageModel
    {
        [TempData] public string Lievelingsgetal { get; set; } = null;

        public IActionResult OnGet()
        {
            if (string.IsNullOrWhiteSpace(Lievelingsgetal))
            {
                return RedirectToPage("SetTempData");
            }

            return Page();
        }
    }
}

Examples/Pages/Lesson1/Cookies.cshtml
@page
@model Examples.Pages.Lesson1.Cookies

@{
    Layout = null;
}

<h1>Counter: @Model.Counter</h1>
<form method="get">
    <button name="action" value="increment" type="submit">Increment ++</button>
    <button name="action" value="decrement" type="submit">Decrement --</button>
    <button name="action" value="reset" type="submit">Reset Cookie</button>
</form>

Examples/Pages/Lesson1/GetRequest.cshtml
@page
@model Examples.Pages.Lesson1.GetRequest

@{
    Layout = null;
}

<h1>Hello @Model.Name</h1>
<form method="get">
    <input name="naam" type="text">
    <button type="submit">Verzenden</button>
</form>
<hr>
<a href="?naam=Lops">Lops</a>

Examples/Pages/Lesson1/HiddenFormFields.cshtml
@page
@model Examples.Pages.Lesson1.HiddenFormFields

@{
    Layout = null;
}

@if (Request.Method == "POST")
{
    <p>productId: @Request.Form["productId"]</p>
    <p>action: @Request.Form["action"]</p>
}

<hr/>
    <p>productId: @Model.ProductId</p>
    <p>action: @Model.ProductId</p>

<hr/>

<form method="post">
    <input type="hidden" name="productId" value="434343">
    <input type="hidden" name="action" value="addItemToShoppingCard">
    <button type="submit">Add Product to Shopping Cart</button>
</form>

Examples/Pages/Lesson1/NonWorkingCounter.cshtml
@page
@model Examples.Pages.Lesson1.NonWorkingCounter

@{
    Layout = null;
}

<h1>Counter: @Model.Counter</h1>

Examples/Pages/Lesson1/PageCentric.cshtml
@page
@model Examples.Pages.Lesson1.PageCentricExample

@{
    Layout = null;
}

<h1>Display Todo Items</h1>

<ul>
@foreach (var todoItem in Model.Todos)
{
    <li>@todoItem.Name -- @todoItem.Completed -- @todoItem.TodoId</li>
}
</ul>

Examples/Pages/Lesson1/PageHandler.cshtml
@page
@model Examples.Pages.Lesson1.PageHandler

@{
    Layout = null;
}

@Model.Counter


@* https://www.learnrazorpages.com/razor-pages/handler-methods *@
@* Take a look at the generated HTML (__RequestVerificationToken)  *@

<h1>Multiple forms, asp-page-handler on the form tag</h1>
<form method="post" asp-page-handler="Increment">
    <input type="hidden" name="count" value="@Model.Counter" >
    <button type="submit">+</button>
</form>

<form method="post" asp-page-handler="Decrement">
    <input type="hidden" name="count" value="@Model.Counter" >
    <button type="submit">-</button>
</form>
<hr>
<h1>Single form, asp-page-handler on the button tag</h1>
<form method="post" >
    <input type="hidden" name="count" value="@Model.Counter" >
    <button type="submit" asp-page-handler="Increment">+</button>
    <button type="submit" asp-page-handler="Decrement">-</button>
</form>
<hr>
<a asp-page-handler="Increment" asp-route-count="@Model.Counter">+</a>
<a asp-page-handler="Decrement" asp-route-count="@Model.Counter">-</a>

Examples/Pages/Lesson1/QueryStringsMethodBindProperty.cshtml
@page
@model Examples.Pages.Lesson1.QueryStringsMethodBindProperty

@{
    Layout = null;
}

<h1>QueryString: @Request.QueryString</h1>

<h1>Firstname: @Model.Firstname</h1>
<h2>MiddleNames: </h2>
<ul>
    @foreach (var middleName in @Model.MiddleNames)
    {
        <li>@middleName</li>
    }
</ul>
<h1>Lastname: @Model.Lastname</h1>
<hr>

<h2>With a form</h2>
<form method="get">
    Voornaam: <input name="firstname"><br>
    Extra naam: <input name="middleNames"><br>
    Extra naam: <input name="middleNames"><br>
    Extra naam: <input name="middleNames"><br>
    Extra naam: <input name="middleNames"><br>
    Achternaam: <input name="lastname"><br>
    <button type="submit">Submit</button>
</form>
<hr>
<h2>With a link</h2>
<a href="?firstname=Joris&middleNames=Daniel&middleNames=Jacob&lastname=Lops">QueryString</a>

<h1>Kijk eens naar de url (adresbalk), kan je de structuur ontdekken?</h1>
<h2>Wat gebeurt er als een spatie staat in een inputbox?</h2>
<h2>Wat gebeurt er met meerdere waarden voor dezelfde key (middleNames)?</h2>

Examples/Pages/Lesson1/QueryStringsMethodRequest.cshtml
@page
@model Examples.Pages.Lesson1.QueryStringsMethodRequest

@{
    Layout = null;
}

<h1>QueryString: @Request.QueryString</h1>

<h1>Firstname: @Model.Firstname</h1>
<h2>MiddleNames:</h2>
<ul>
    @foreach (var middleName in @Model.MiddleNames)
    {
        <li>@middleName</li>
    }
</ul>
<h1>Lastname: @Model.Lastname</h1>
<hr>

<h2>With a form</h2>
<form method="get">
    Voornaam: <input name="firstname"><br>
    Extra naam: <input name="middleNames"><br>
    Extra naam: <input name="middleNames"><br>
    Extra naam: <input name="middleNames"><br>
    Extra naam: <input name="middleNames"><br>
    Achternaam: <input name="lastname"><br>
    <button type="submit">Submit</button>
</form>
<hr>
<h2>With a link</h2>
<a href="?firstname=Joris&middleNames=Daniel&middleNames=Jacob&lastname=Lops">QueryString</a>

<h1>Kijk eens naar de url (adresbalk), kan je de structuur ontdekken?</h1>
<h2>Wat gebeurt er als een spatie staat in een inputbox?</h2>
<h2>Wat gebeurt er met meerdere waarden voor dezelfde key (middleNames)?</h2>

Examples/Pages/Lesson1/RazorSyntax.cshtml
@page
@* @model Examples.Pages.Lesson1.RazorSyntax *@

@{
    Layout = null;
}


<h2>Implicit Razor expressions</h2>

<p>Current DateTime: @DateTime.Now</p>
<p>IsLeapYear(2016): @DateTime.IsLeapYear(2016)</p>

<hr>

<h2>Explicit Razor expressions</h2>
<p>Tomorrow @(DateTime.Now - TimeSpan.FromDays(1))</p>

<hr/>

<h2>Code Block</h2>

@{
  var x = "Hello World";
}
<p>@x</p>
@{
    x = "Goodbye";
}
<p>@x</p>
<hr/>

<p>Last week this time: @(DateTime.Now - TimeSpan.FromDays(7))</p>

@{
    var joe = new Person("Joe", 33);
}

<p>Age@(joe.Age)</p>
<hr/>

@{
    RenderItem("Item 1");
}

@for(int i = 1; i < 3; i++)
{
    RenderItem("Item " +i);
}

<br>
<h2>Transitions (from HTML to C# and back)</h2>
@{
    var inCSharp = true;
    <p>Now in HTML, was in C# @inCSharp</p>
}

@{
    var people = new Person[]
    {
        new Person("Joris", 30),
        new Person("Martin", 40),
        new Person("Jos", 50)
    };
}


@for (var i = 0; i < people.Length; i++)
{
    var person = people[i];
    <p>Name: @person.Name</p>
}

<hr>
<h2>Control Structures & looping (if, else, switch, for, foreach, etc)</h2>

@foreach (var person in people)
{
    if (person.Name.StartsWith("J"))
    {
        <p><b>@person.Name</b></p>
    }
    else
    {
        <p>@person.Name</p>
    }
}


@functions {
    public class Person
    {
        public int Age { get; set; }
        public string Name { get; set; }

        public Person(string name, int age)
        {
            Name = name;
            Age = age;
        }
    }

    public string DisplayPerson(Person p)
    {
        return $"{p.Name} -- {p.Age}";
    }

    void RenderItem(string item) {
        <li>@item</li>
    }
}

Examples/Pages/Lesson1/Redirect.cshtml
@page
@model Examples.Pages.Lesson1.Redirect

@{
    Layout = null;
}

@Model.Count

Examples/Pages/Lesson1/SendDataWithRequest.cshtml
@page
@model Examples.Pages.Lesson1.PostRequestWithParameterBinding

@{
    Layout = null;
}

<h1>Hello @Model.Firstname, @Model.Surname</h1>
<h2>Aka @Model.Nickname @Model.NicknameGet</h2>

<hr>
<h1>Post Form:</h1>
<form method="post">
    Firstname: <input type="text" name="firstname"><br>
    Surname: <input type="text" name="surname"><br>
    Nickname: <input type="text" name="nickname"><br>
    <button type="submit">Submit</button>
</form>

<hr>

<form method="get">
    Firstname: <input type="text" name="firstname"><br>
    Surname: <input type="text" name="surname"><br>
    Nickname: <input type="text" name="nicknameGet"><br>
    <button type="submit">Submit</button>
</form>

Examples/Pages/Lesson1/SessionStoreObject.cshtml
@page
@model Examples.Pages.Lesson1.SessionStoreObject

@{
    Layout = null;
}

<form method="get">
    <button name="action" value="increment">++</button>
    <button name="action" value="decrement">--</button>
    <button name="action" value="reset">x</button>
    <br>
    <button name="action" value="removeSession">Delete Session</button>
</form>
<hr>
@Model.ActionCounter.CalculateResult()
<hr>
@if (Model.ActionCounter.Actions.Count > 0)
{
    <ul>
    @foreach (var action in Model.ActionCounter.Actions)
    {
        <li>@action</li>
    }
    </ul>
}

Examples/Pages/Lesson1/SetTempData.cshtml
@page
@model Examples.Pages.Lesson1.SetTempData

@{
    Layout = null;
}

<h1>Kies je lievelingsgetal</h1>
<ul>
    @foreach (var getal in Enumerable.Range(1, 10))
    {
        <li>
            <form method="post">
                @getal
                <button type="submit" name="lievelingsgetal" value="HalloWorld@getal">Selecteer</button>
            </form>
        </li>
    }
</ul>

Examples/Pages/Lesson1/ShowTempData.cshtml
@page
@model Examples.Pages.Lesson1.ShowTempData

@{
    Layout = null;
}


@if (!string.IsNullOrWhiteSpace((string?) TempData["Lievelingsgetal"]))
{
    <h1>Je lievelingsgetal is: @TempData["Lievelingsgetal"]</h1>
}

@if (!string.IsNullOrWhiteSpace(Model.Lievelingsgetal))
{
    <!-- De techniek met een proprety heeft mijn voorkeur -->
    <h1>Je lievelingsgetal is: @Model.Lievelingsgetal</h1>
}