Examples/Pages/Lesson2/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson2
{
    public class Index : PageModel
    {
        public void OnGet()
        {
            
        }
    }
}

Examples/Pages/Lesson2/Products/Create.cshtml.cs
using System.Collections.Generic;
using Examples.Pages.Lesson2.Models;
using Examples.Pages.Lesson2.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson2.Products
{
    public class Create : PageModel
    {
        private readonly ProductsRepository _productRepository;

        [BindProperty]
        public Product Product { get; set; }

        public List<Category> Categories { get; set; }

        public Create()
        {
            _productRepository = new ProductsRepository();
        }

        public void OnGet()
        {
            Categories = _productRepository.GetCategories();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _productRepository.AddProduct(Product);

            return RedirectToPage("Index");
        }
    }
}

Examples/Pages/Lesson2/Products/Index.cshtml.cs
using System.Collections.Generic;
using Examples.Pages.Lesson2.Models;
using Examples.Pages.Lesson2.Repositories;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson2.Products
{
    public class Index : PageModel
    {
        private readonly ProductsRepository _productRepository;
        public IEnumerable<Product> Products { get; set; }

        public Index()
        {
            _productRepository = new ProductsRepository();
        }

        public void OnGet()
        {
            Products = _productRepository.GetProductsInShop();
        }

        public void OnPostDelete(int productId)
        {
            Products = _productRepository.DeleteProduct(productId);
        }
    }
}

Examples/Pages/Lesson3/Create.cshtml.cs
using System.Collections.Generic;
using Examples.Pages.Lesson3.Models;
using Examples.Pages.Lesson3.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Examples.Pages.Lesson3
{
    public class Create : PageModel
    {
        [BindProperty]
        public Product Product { get; set; }

        [TempData]
        public string ProductMessage { get; set; }

        public List<Category> Categories { get; set; }

        public void OnGet()
        {
            Categories = CategoryRepository.GetCategories();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var addProduct = ProductsRepository.AddProduct(Product);

            ProductMessage = $"Het volgende product is toegevoegd : {addProduct.Name}";

            return RedirectToPage("Index");
        }



    }
}

Examples/Pages/Lesson2/Products/Create.cshtml
@page
@model Examples.Pages.Lesson2.Products.Create

@{
    Layout = "_Layout";
}

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />

    <script>
    var settings = {
        validClass: "is-valid",
        errorClass: "is-invalid"
    };
    $.validator.setDefaults(settings);
    $.validator.unobtrusive.options = settings;
    </script>
}

<form method="post">
    <div class="form-group">
        <label asp-for="Product.Name"></label>
        <input asp-for="Product.Name" class="form-control">
        <span class="invalid-feedback" asp-validation-for="Product.Name"></span>
    </div>

    <div class="form-group">
        <label asp-for="Product.Description"></label>
        <input asp-for="Product.Description" class="form-control" placeholder="Enter product description">
        <span class="invalid-feedback" asp-validation-for="Product.Description"></span>
    </div>

    <div class="form-group">
        <label asp-for="Product.Price"></label>
        <input asp-for="Product.Price" class="form-control" placeholder="Enter product price">
        <span class="invalid-feedback" asp-validation-for="Product.Price"></span>
    </div>

    <div class="form-group">
        <label asp-for="Product.SalePrice"></label>
        <input asp-for="Product.SalePrice" class="form-control" placeholder="Optional Enter Sales price">
        <span class="invalid-feedback" asp-validation-for="Product.SalePrice"></span>
    </div>

    <div class="form-group">
        <label asp-for="Product.InShopDate"></label>
        @* https://stackoverflow.com/questions/59637348/datetime-default-value-asp-net-core *@
        <input asp-for="Product.InShopDate" value="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control">

        <span class="invalid-feedback" asp-validation-for="Product.InShopDate"></span>
    </div>

    <div class="form-group">
     <label asp-for="Product.CategoryId"></label>
     <select class="form-control"
             asp-for="Product.CategoryId"
             asp-items="Model.Categories.Select(x => new SelectListItem() {
                 Text = x.Name,
                 Value = x.CategoryId.ToString()})">
     </select>
     <span class="invalid-feedback" asp-validation-for="Product.CategoryId"></span>
    </div>

@*     <div class="form-group"> *@
@*         <select asp-for="Product.CategoryId" class="form-control"> *@
@*             @foreach (var category in Model.Categories) *@
@*             { *@
@*                 <option value="@category.CategoryId">@category.Name</option> *@
@*             } *@
@*         </select> *@
@*     </div> *@

    <button class="btn btn-primary" type="submit">Add</button>
</form>

Examples/Pages/Lesson2/Products/Index.cshtml
@page
@model Examples.Pages.Lesson2.Products.Index

@{
    Layout = "Products/_ProductsLayout";
}

<h1>All Category Infos</h1>
@await Component.InvokeAsync("CategoryInfoComponent")

<h1>Products</h1>
<partial name="_ProductCount" model="Model.Products"/>

<div class="row">
    @foreach (var product in Model.Products)
    {
        <div class="col-md-4">
            <div class="card mb-3">
                <div class="card-header">
                    @product.Name
                </div>
                <img class="card-img-top" src="https://picsum.photos/id/@(product.ProductId)/200/200" alt="@product.Name">
                <div class="card-body">
                    @if (@product.SalePrice.HasValue)
                    {
                        <h2 class="card-subtitle text-info">@product.SalePrice <del>@product.Price</del></h2>
                    }
                    else
                    {
                        <h2 class="card-subtitle text-info">@product.Price</h2>
                    }
                    <p class="card-text">@product.Description</p>
                    <form method="post">
                        <input type="hidden" name="productId" value="@product.ProductId">
                        <button asp-page-handler="Delete" class="btn btn-primary">Delete</button>
                    </form>
                    <a asp-page="./Edit" asp-route-id="@product.ProductId" class="btn btn-primary">Edit</a>
                </div>
                <div class="card-footer">
                      <small class="text-muted">@product.Category</small>
                </div>
            </div>
        </div>
    }
</div>

Examples/Pages/Lesson2/Products/_ProductCount.cshtml
@model List<Examples.Pages.Lesson2.Models.Product>

<h2>Aantal Producten @Model.Count()</h2>

Examples/Pages/Lesson2/Products/_ProductsLayout.cshtml
@{
    Layout = "Shared/_Layout";
}

<h1>Products Layout</h1>

<h1>Category Info for Category 1, see _ProductLayout.cshtml</h1>
@await Component.InvokeAsync("CategoryInfoComponent", "Category 1")



@RenderBody()